# Generated by Django 4.1.7 on 2023-02-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update time')),
                ('part_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Name auto part')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='auto_parts_images/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, verbose_name='Price')),
                ('available_quantity', models.PositiveIntegerField(default=0, verbose_name='Available quantity')),
                ('category', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.PROTECT, to='auto_parts.category')),
            ],
            options={
                'verbose_name': 'AutoPart',
                'verbose_name_plural': 'AutoParts',
                'ordering': ['name'],
            },
        ),
    ]
